### ISSUE TITLE
Сжатый файл читается без ошибки декомпрессии, но данные временных меток битые

### ISSUE THREAD

**Issue by NewYaroslav** [NewYaroslav/binary-cpp-api#5]
Надо выяснить, как такое вообще может быть. Временная метка читается битой
Файл для примера:
frxEURUSD/2019_1_21.zstd

**Comment by LimiNode** [comment]
Дело однозначно не в битых файлах. Файл можно читать нормально, но иногда он читается с ошибкой. Ошибка возникает именно во временной метке, которая читается последней.

``C++
double dtemp;
unsigned long long lltemp;
std::memcpy(&dtemp, (unsigned char*)buffer + buffer_offset, sizeof(double));
prices[i] = dtemp;
buffer_offset += sizeof(double);
std::memcpy(&lltemp, (unsigned char*)buffer + buffer_offset, sizeof(unsigned long long));
times[i] = lltemp;
std::cout << dtemp << " " << lltemp << " " << i << " " << data_size << std::endl;
buffer_offset += sizeof(unsigned long long);
``

**Comment by LimiNode** [comment]
Ошибка возникает в std::memcpy

**Comment by LimiNode** [comment]
Ошибка вызвана тем, что кое кто забыл юзнуть memset, чтобы заполнить буфер нулями.
